In [2]:
import numpy as np
import tensorflow as tf
import random as rm

In [3]:
import os
os.environ['PYTHONHASHSEED'] = '0'

In [4]:
# Setting the seed for numpy-generated random numbers
np.random.seed(37)

In [6]:
# Setting the seed for Python random numbers
rm.seed(1254)

In [7]:
# Setting the seed for Tensorflwo randoem numbers
tf.set_random_seed(89)

In [11]:
from keras import backend as K
# force Tensorflow to use a single thread
sess = tf.Session(graph=tf.get_default_graph())
K.set_session(sess)

## Bias

In [12]:
from keras.models import Sequential
from keras.layers import Dense, Activation

In [14]:
model = Sequential([
    Dense(4, input_shape=(1,), activation='relu', use_bias=True, bias_initializer = 'zeros'),
    Dense(2, activation='softmax')
])

In [15]:
model.get_weights()

[array([[-0.5333039, -0.8589198,  0.0159899, -0.6266952]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.56253076,  0.3659532 ],
        [ 0.673604  , -0.47082686],
        [-0.6892462 ,  0.19190264],
        [ 0.8937402 ,  0.9475126 ]], dtype=float32),
 array([0., 0.], dtype=float32)]